### ISSUE TITLE
使用宏重定义国际化方法的问题

### ISSUE THREAD

**Issue by dustturtle** [Aufree/Hodor#3]
使用系统的方法我们可以使用genstrings配合完成国际化的工作，使用宏重定义后该工具就不能使用了。对于这块的优化作者有没有啥想法或者实践啊?

**Comment by Aufree** [comment]
试下 -s 参数

![image](https://cloud.githubusercontent.com/assets/5310542/20781830/2b8f5b42-b7c1-11e6-99ef-0094ffea482c.png)

**Comment by dustturtle** [comment]
-s 参数需要重写的宏后缀是按照指定格式，且参数也必须包含comment

**Comment by Aufree** [comment]
写了个简单的 [Ruby 脚本](https://github.com/Aufree/Hodor/blob/master/update_strings.rb) 来匹配使用了 `kLang` 的字符串，并支持对 `strings` 文件的增量更新操作，你可以根据自己的实际需求进行调整。

可通过进入此项目的根目录，运行下面命令来执行该脚本:

```bash
$ ruby update_strings.rb
```

**Comment by dustturtle** [comment]
回头用一下看看。多谢哒！
